# Generated by Django 3.1.7 on 2021-03-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='sort_order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
