# Generated by Django 3.1.7 on 2021-03-15 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0002_auto_20210312_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='social-icons')),
                ('link', models.URLField(max_length=350)),
            ],
        ),
    ]
