# Generated by Django 3.2 on 2021-04-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0004_auto_20210417_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-startDate', '-endDate', '-startTime', '-endTime']},
        ),
    ]
