# Generated by Django 3.1.7 on 2021-03-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0005_auto_20210315_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='icon',
            new_name='picture',
        ),
    ]
