# Generated by Django 3.2 on 2021-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0005_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='role',
            field=models.CharField(default='Empty', max_length=100),
            preserve_default=False,
        ),
    ]
