# Generated by Django 3.1.7 on 2021-04-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('edit', '0007_auto_20210423_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={},
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='%(class)s-pictures', width_field='width'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='%(class)s-pictures', width_field='width'),
        ),
    ]
