# Generated by Django 3.1.7 on 2021-04-25 15:34

from django.db import migrations, models

import edit.models


class Migration(migrations.Migration):
    dependencies = [
        ('edit', '0008_auto_20210425_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallink',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='picture',
            field=models.ImageField(height_field='height', upload_to=edit.models.get_upload_to, width_field='width'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='picture',
            field=models.ImageField(height_field='height', upload_to=edit.models.get_upload_to, width_field='width'),
        ),
    ]
