# Generated by Django 3.1.7 on 2021-03-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0008_auto_20210316_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ['date_posted']},
        ),
    ]
