# Generated by Django 3.1.7 on 2021-03-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0010_auto_20210319_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['dateOf', 'startTime']},
        ),
    ]
