# Generated by Django 3.1.7 on 2021-03-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0011_auto_20210319_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
