# Generated by Django 3.1.7 on 2021-03-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0015_auto_20210323_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='service',
            field=models.CharField(choices=[('TW', 'Twitter'), ('IG', 'Instagram'), ('YT', 'YouTube'), ('FB', 'Facebook'), ('LI', 'Linkedin'), ('PT', 'Pinterest')], default='TW', max_length=2),
        ),
    ]
