# Generated by Django 3.1.7 on 2021-03-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0016_auto_20210323_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-dateOf', '-startTime']},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['sort_order']},
        ),
    ]
